site_name: DipCoin Python Docs

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/your-repo
      name: GitHub
      target: _blank
      rel: noopener noreferrer

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [dipcoin]

nav:
  - Get Started: get_started.md
  - Tutorial: tutorials.md
  - Reference: reference.md
